# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "clicksrv"
subtitle: "See the world through my eyes!"
author: "Saurav Kumar Sahoo"
header:
 title: "Photography"
 subtitle: "by Saurav Kumar Sahoo"
footer:
 name: "Hey there, my name is Saurav"
 bio: "I am a software developer with a zing for photography. Hope you enjoy this visual journey with me!"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/clicksrv"
  linkedin: "https://in.linkedin.com/in/sauravkumarsahoo"
  github: "https://www.github.com/clicksrv"
